Update script

diff --git a/script b/script
--- a/script
+++ b/script
@@ -2,97 +2,64 @@
 
 # Function to display script usage/help information
 function display_usage() {
-  echo "Usage: ./my_script.sh -f <filename> -o <output_dir> -t <type>"
+  echo "Usage: ./loganalyzer.sh -f <filename>"
   echo "Options:
-  -f <filename>: Specify the input filename.
-  -o <output_dir>: Specify the output directory where the results will be stored.
-  -t <type>: Specify the type of action to perform. Supported types are 'process' and 'analyze'.
+  -f <filename>: Specify the log filename.
   -h: Display this help information."
 }
 
-
-# Check if no arguments are provided.
-# If so, display usage information and exit
-
-
-if [ $# -eq 0 ]; then
-    display_usage
-    exit 1
-fi
-
 # Initialize variables
 filename=""
-output_dir=""
-action=""
+alerts='[Ee]rror|[Ww]arning'
 
-# Process command-line options and arguments
-while getopts ":f:o:t:h" opt; do
-    case $opt in
-        f)
-            # option f
-            filename="$OPTARG"
-            ;;
-        o)
-           # option o
-            output_dir="$OPTARG"
-            ;;
-        t)
-          # option t
-            action="$OPTARG"
-            ;;
-        h)
-           # option h
-            # display usage and exit
-            display_usage
-            exit 0
-            ;;
-        \?)
-            # any other option
-            echo "Invalid option: -$OPTARG"
-             # display usage and exit
-            display_usage
-            exit 1
-            ;;
-    esac
+
+while getopts ":f:h" opt; do
+  case $opt in
+    f)
+      filename="$OPTARG"
+      ;;
+    h)
+      display_usage
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      display_usage
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      display_usage
+      exit 1
+      ;;
+  esac
 done
 
-# Check if all required switches are provided
- if [[ ! "$filename" || ! "$output_dir" || ! "$action" ]]; then
-    echo "Error: Missing required options."
-    # display usage and exit
-    display_usage
-    exit 1
+# Check if filename was input
+if [ -z "$filename" ]; then
+  echo "Error: Please provide a filename."
+  display_usage
+  exit 1
 fi
-   
 
-# Check if the -t switch has a valid argument
-if [[ "$action" != "process" && "$action" != "analyze" ]]; then
-    echo "Error: Invalid action type. Supported types are 'process' and 'analyze'."
-     # exit
-    exit 1
-fi
-   
-
-# Check if the specified input filename exists and is a regular file
+# Check if the file exists in system
 if [ ! -f "$filename" ]; then
-    echo "Error: Input file '$filename' does not exist or is not a regular file."
-     # exit
-    exit 1
+  echo "File '$filename' does not exist. "
+  display_usage
+  exit 1
 fi
-   
 
-# Check if the specified output directory exists and is a directory
-if [ ! -d "$output_dir" ]; then
-    echo "Error: Output directory '$output_dir' does not exist."
-    # exit
-    exit 1
-fi
-   
+# If file exists, print information
+echo "File Information:"
+FILESIZE=$(stat -c%s "$filename") 
+echo "Size: $FILESIZE"
+perm=$(chmod go-rw  "$filename") 
+echo "Permissions: $perm"
+mod=$(stat -c %y "$filename") 
+echo "Modified: $mod"
 
-# Perform the selected action based on the user input
-# if action is process
-    if [ "$action" = "process" ]; then
-    echo "Processing task will be performed on '$filename' and the results will be stored in '$output_dir'."
-# else if action is analyze
-    elif [ "$action" = "analyze" ]; then
-    echo "Analysis will be performed on '$filename' and the report will be stored in '$output_dir'."
+# Analyze log file
+echo "Log Analysis Results:"
+count=$(awk -v pattern="$alerts" '$0 ~ pattern' "$filename" | grep -vE '^[[:space:]]*$' | sort | uniq -c | sort -nr)
+echo "$count"
+
